version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
      time: '06:00'
      timezone: Europe/Warsaw
    open-pull-requests-limit: 10
    target-branch: 'developer'
    reviewers:
      - rskrzypczak
      - mariuszkrzaczkowski
    assignees:
      - rskrzypczak
      - mariuszkrzaczkowski
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
      time: '06:00'
      timezone: Europe/Warsaw
    open-pull-requests-limit: 10
    target-branch: 'developer'
    reviewers:
      - rskrzypczak
      - mariuszkrzaczkowski
    assignees:
      - rskrzypczak
      - mariuszkrzaczkowski
