version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 10
  reviewers:
  - rskrzypczak
  assignees:
  - rskrzypczak
  ignore:
  - dependency-name: smarty/smarty
    versions:
    - 3.1.38
    - 3.1.39
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: yetiforce/csrf-magic
    versions:
    - 1.1.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 10
  reviewers:
  - rskrzypczak
  - mariuszkrzaczkowski
  assignees:
  - rskrzypczak
  - mariuszkrzaczkowski
  ignore:
  - dependency-name: datatables.net-bs4
    versions:
    - 1.10.23
  - dependency-name: chartjs-plugin-datalabels
    versions:
    - 0.7.0
